### ISSUE TITLE
Bug: Errors in faucet with `test-migrate-elsa-to-biarritz-rc1` and `test-migrate-biarritz-rc1-to-pre-l1-merge`

### ISSUE THREAD

**Issue by andygolay** [movementlabsxyz/movement-migration#50]
Bugs occur for me in the following tests (most are on main, just the pre-l1-merge related ones are on the branch for [1212](https://github.com/movementlabsxyz/movement/pull/1212).

When I run 

```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.setup.eth-local.celestia-local.test-migrate-elsa-to-biarritz-rc1 --keep-tui"
```

or

```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.setup.eth-local.celestia-local.test-migrate-biarritz-rc1-to-pre-l1-merge --keep-tui"
```

or

```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.setup.eth-local.celestia-local.test-migrate-elsa-to-biarritz-rc1 --keep-tui"
```

I get the same faucet error:
```
Error: Failed to build Funder

Caused by:
0: Failed to build MintFunder
1: Failed to make MintFunder use delegated account
2: Failed to delegate minting to the new account
3: Unknown error Transaction committed on chain, but failed execution: Move abort in 0x1::system_addresses: ENOT_APTOS_FRAMEWORK_ADDRESS(0x50003): The address/account did not correspond to the core framework address
```

<img width="649" alt="Image" src="https://github.com/user-attachments/assets/81f94325-7708-4ccd-9ed3-27995630da4f" />

When I run the stack without either test, the faucet runs correctly. The tests are aways in pending state until they are skipped when the faucet fails.

The only test that passes is `test-bring-up-elsa-to-biarritz-rc1` eg
```
CELESTIA_LOG_LEVEL=FATAL nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just movement-full-node native build.setup.eth-local.celestia-local.test-bring-up-biarritz-rc1-to-pre-l1-merge --keep-tui"
```
I noticed that `test-bring-up-elsa-to-biarritz-rc1` runs the Clap command to upgrade from Elsa to Biarritz RC1, and so I'm wondering is that a fine pattern to use to test framework upgrades?

Hmm it looks like the faucet works for `test-upgrade-biarritz-rc1`. Maybe that would be a good one to model. 

<img width="652" alt="Image" src="https://github.com/user-attachments/assets/b690efdd-027c-46fb-9923-aeece9253cf0" />

That test past. There are no env vars set up; the command run is `cargo run --bin aptos-framework-biarritz-rc1-release-tool` which runs that release's [`release.rs`](https://github.com/movementlabsxyz/movement/blob/main/protocol-units/execution/maptos/framework/releases/biarritz-rc1/src/bin/release.rs). I'll try working with this one as it follows a pattern similar to `test-migrate-biarritz-rc1-to-pre-l1-merge`.

All of the above tests should pass.

**Comment by andygolay** [comment]
One thing I noticed in ` test-migrate-biarritz-rc1-to-pre-l1-merge` is that if I comment out the env vars, it passes:

```
version: "3"

processes:

  setup:
    environment:
      # - "KNOWN_FRAMEWORK_RELEASE=biarritz-rc1"
      # - APTOS_ACCOUNT_WHITELIST=$DOT_MOVEMENT_PATH/default_signer_address_whitelist
      # - MAPTOS_PRIVATE_KEY=random

  test-migrate-biarritz-rc1-to-pre-l1-merge:
    command: |
      cargo run --bin aptos-framework-pre-l1-merge-release-tool
    depends_on:
      movement-full-node:
        condition: process_healthy
      movement-faucet:
        condition: process_healthy
```

But if I uncomment them, I get the faucet error. Even if I only uncomment `- "KNOWN_FRAMEWORK_RELEASE=biarritz-rc1"`, it still gives the faucet error.

<img width="665" alt="Image" src="https://github.com/user-attachments/assets/78780380-6019-4e39-9239-c55ba2804c78" />

**Comment by andygolay** [comment]
Update: if I comment out ` test-migrate-elsa-to-biarritz-rc1` as follows:

```
version: "3"

processes:

  setup:
    environment:
      - "KNOWN_FRAMEWORK_RELEASE=elsa"
      # - APTOS_ACCOUNT_WHITELIST=$DOT_MOVEMENT_PATH/default_signer_address_whitelist
      # - MAPTOS_PRIVATE_KEY=random
```

Then I get past the faucet error in that test. The test appears to succeed, reaching `Voted through release`:

<img width="1148" alt="Image" src="https://github.com/user-attachments/assets/b707ebed-1ce4-45ec-9370-51dc3406799c" />
